KS-2-3
KotlinTest1/KotlinSprint1 pull request #7
Opened 2023-09-08 06:47 UTC by KotlinTest1

arrival time, это такой колхоз, но я не смог понять, как правильно высчитать остаток

2023-09-08 14:17 UTC, ievetrov requested changes
Подскажу в качестве исключения по более оптимальному решению, чтобы слишком долго не задерживаться тут) Можно решить задачу, например, вот так. Но с вашими переменными
```
val arrivalHours = (departureHours + (departureMinutes + travelTime) / 60) % 24
val arrivalMinutes = (departureMinutes + travelTime) % 60
```
Не забудьте учесть остальные правки в комментариях

2023-09-08 14:17 UTC, ievetrov commented on src/main/kotlin/lesson2/lesson2-task3.kt
> +    var oneHour = 60
хорошая идея вынести повторяющееся значение в отдельную переменную, но так как оно точно никогда не может быть изменено, предлагаю вынести его в константу)

2023-09-08 14:17 UTC, ievetrov commented on src/main/kotlin/lesson2/lesson2-task3.kt
> +    val separation: String = ":"
разделитель давай уберем из переменных. конечную строку будем формировать с помощью интерполяции

2023-09-08 14:26 UTC, KotlinTest1 commented on src/main/kotlin/lesson2/lesson2-task3.kt
> +    val separation: String = ":"
Про интерполяцию во 2 уроке же нечего не было сказано, или я просто невнимательно смотрел? Не могу понять, что это значит

2023-09-10 09:43 UTC, ievetrov approved these changes

2023-10-18 07:56 UTC, merged